---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    yum_timeout: 3600

platforms:
  - name: centos-5.10
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[lumenvox]
    attributes:
